# Generated by Django 5.0.1 on 2024-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='landmarkWeb/images/'),
        ),
    ]
