# Generated by Django 5.0.1 on 2024-01-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarkWeb', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='landmarkModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='static/landmarkWeb/images/media/user_uploaded_images'),
        ),
    ]
